#!/usr/bin/env python3
"""
HELLDECK Gold Card Quality Fix
Based on Comedy Science Research (Benign Violation Theory + Specificity)

This script fixes/replaces low-quality gold cards with comedy-science-backed versions.
"""

import json
from pathlib import Path

GOLD_CARDS_PATH = Path(__file__).parent.parent / "app/src/main/assets/gold/gold_cards.json"

# ============================================================================
# REALITY CHECK - Complete rewrite needed (current cards are generic)
# Principle: Dunning-Kruger effect + Observable behaviors + Specific scenarios
# ============================================================================

REALITY_CHECK_CARDS = [
    # SKILLS PEOPLE OVERRATE
    {"id": "reality_check_new_1", "game": "REALITY_CHECK", "family": "reality_check", 
     "text": "Rate your ability to parallel park while someone watches from the sidewalk", "spice": 2, "locality": 1, "quality_score": 9},
    {"id": "reality_check_new_2", "game": "REALITY_CHECK", "family": "reality_check",
     "text": "Rate how well your jokes land in a group text where no one responds", "spice": 3, "locality": 1, "quality_score": 9},
    {"id": "reality_check_new_3", "game": "REALITY_CHECK", "family": "reality_check",
     "text": "Rate your driving while merging onto the highway with a passenger gripping the handle", "spice": 2, "locality": 1, "quality_score": 9},
    {"id": "reality_check_new_4", "game": "REALITY_CHECK", "family": "reality_check",
     "text": "Rate how edible your Thanksgiving dish would be if Gordon Ramsay was at the table", "spice": 2, "locality": 1, "quality_score": 9},
    {"id": "reality_check_new_5", "game": "REALITY_CHECK", "family": "reality_check",
     "text": "Rate your ability to give directions without using your hands", "spice": 2, "locality": 1, "quality_score": 8},
    {"id": "reality_check_new_6", "game": "REALITY_CHECK", "family": "reality_check",
     "text": "Rate your dancing when you think no one is watching vs when everyone is", "spice": 3, "locality": 1, "quality_score": 9},
    {"id": "reality_check_new_7", "game": "REALITY_CHECK", "family": "reality_check",
     "text": "Rate your flirting skills according to the last person you tried to flirt with", "spice": 4, "locality": 1, "quality_score": 9},
    {"id": "reality_check_new_8", "game": "REALITY_CHECK", "family": "reality_check",
     "text": "Rate how often your 'quick errands' actually take under 30 minutes", "spice": 2, "locality": 1, "quality_score": 8},
    # SOCIAL SELF-AWARENESS
    {"id": "reality_check_new_9", "game": "REALITY_CHECK", "family": "reality_check",
     "text": "Rate how interesting your stories are to people who didn't ask", "spice": 3, "locality": 1, "quality_score": 9},
    {"id": "reality_check_new_10", "game": "REALITY_CHECK", "family": "reality_check",
     "text": "Rate how quietly you actually chew according to the person sitting next to you at dinner", "spice": 3, "locality": 1, "quality_score": 9},
    {"id": "reality_check_new_11", "game": "REALITY_CHECK", "family": "reality_check",
     "text": "Rate how well you can read the room when you've been talking for 10 minutes straight", "spice": 3, "locality": 1, "quality_score": 9},
    {"id": "reality_check_new_12", "game": "REALITY_CHECK", "family": "reality_check",
     "text": "Rate your ability to not interrupt people mid-sentence", "spice": 3, "locality": 1, "quality_score": 8},
    {"id": "reality_check_new_13", "game": "REALITY_CHECK", "family": "reality_check",
     "text": "Rate how long your 'just one more episode' actually lasts", "spice": 2, "locality": 1, "quality_score": 8},
    {"id": "reality_check_new_14", "game": "REALITY_CHECK", "family": "reality_check",
     "text": "Rate your poker face when someone shows you their ugly baby", "spice": 4, "locality": 1, "quality_score": 9},
    {"id": "reality_check_new_15", "game": "REALITY_CHECK", "family": "reality_check",
     "text": "Rate how often you actually return the shopping cart to the corral", "spice": 2, "locality": 1, "quality_score": 8},
    # TECH/MODERN LIFE
    {"id": "reality_check_new_16", "game": "REALITY_CHECK", "family": "reality_check",
     "text": "Rate how quickly you respond to texts vs how quickly you expect others to", "spice": 3, "locality": 1, "quality_score": 9},
    {"id": "reality_check_new_17", "game": "REALITY_CHECK", "family": "reality_check",
     "text": "Rate your ability to take just one photo and not 47 nearly identical ones", "spice": 2, "locality": 1, "quality_score": 8},
    {"id": "reality_check_new_18", "game": "REALITY_CHECK", "family": "reality_check",
     "text": "Rate your screen time vs what you think your screen time is", "spice": 2, "locality": 1, "quality_score": 8},
    {"id": "reality_check_new_19", "game": "REALITY_CHECK", "family": "reality_check",
     "text": "Rate how well you'd do if someone watched you try to fold a fitted sheet", "spice": 2, "locality": 1, "quality_score": 9},
    {"id": "reality_check_new_20", "game": "REALITY_CHECK", "family": "reality_check",
     "text": "Rate your email professionalism when you're actually seething with rage", "spice": 3, "locality": 1, "quality_score": 9},
    # HABITS AND BEHAVIORS
    {"id": "reality_check_new_21", "game": "REALITY_CHECK", "family": "reality_check",
     "text": "Rate how often you 'forget' to reply vs intentionally ignore the message", "spice": 4, "locality": 1, "quality_score": 9},
    {"id": "reality_check_new_22", "game": "REALITY_CHECK", "family": "reality_check",
     "text": "Rate how often your '5 more minutes' snooze turns into an hour", "spice": 2, "locality": 1, "quality_score": 8},
    {"id": "reality_check_new_23", "game": "REALITY_CHECK", "family": "reality_check",
     "text": "Rate how subtle you think you are when checking someone out", "spice": 4, "locality": 1, "quality_score": 9},
    {"id": "reality_check_new_24", "game": "REALITY_CHECK", "family": "reality_check",
     "text": "Rate your ability to whisper in a movie theater vs how loud you actually are", "spice": 2, "locality": 1, "quality_score": 8},
    {"id": "reality_check_new_25", "game": "REALITY_CHECK", "family": "reality_check",
     "text": "Rate how often you actually 'just woke up' in your good morning selfies", "spice": 3, "locality": 1, "quality_score": 9},
    # SELF-PERCEPTION GAP
    {"id": "reality_check_new_26", "game": "REALITY_CHECK", "family": "reality_check",
     "text": "Rate your outfit choices according to old photos from 5 years ago", "spice": 2, "locality": 1, "quality_score": 8},
    {"id": "reality_check_new_27", "game": "REALITY_CHECK", "family": "reality_check",
     "text": "Rate how often your 'I'm almost there' is actually true", "spice": 3, "locality": 1, "quality_score": 9},
    {"id": "reality_check_new_28", "game": "REALITY_CHECK", "family": "reality_check",
     "text": "Rate your ability to stick to a bedtime you set for yourself", "spice": 2, "locality": 1, "quality_score": 8},
    {"id": "reality_check_new_29", "game": "REALITY_CHECK", "family": "reality_check",
     "text": "Rate how often your 'I never do this' is actually something you do all the time", "spice": 4, "locality": 1, "quality_score": 9},
    {"id": "reality_check_new_30", "game": "REALITY_CHECK", "family": "reality_check",
     "text": "Rate your ability to pronounce 'quinoa' confidently in public", "spice": 2, "locality": 1, "quality_score": 8},
    # MORE OBSERVABLE BEHAVIORS
    {"id": "reality_check_new_31", "game": "REALITY_CHECK", "family": "reality_check",
     "text": "Rate how put-together you look in your Zoom background vs your actual room", "spice": 2, "locality": 1, "quality_score": 8},
    {"id": "reality_check_new_32", "game": "REALITY_CHECK", "family": "reality_check",
     "text": "Rate how many of your New Year's resolutions make it to February", "spice": 2, "locality": 1, "quality_score": 8},
    {"id": "reality_check_new_33", "game": "REALITY_CHECK", "family": "reality_check",
     "text": "Rate your ability to not look at your phone during a movie", "spice": 2, "locality": 1, "quality_score": 8},
    {"id": "reality_check_new_34", "game": "REALITY_CHECK", "family": "reality_check",
     "text": "Rate how well you handle being wrong in an argument you were 'definitely' right about", "spice": 3, "locality": 1, "quality_score": 9},
    {"id": "reality_check_new_35", "game": "REALITY_CHECK", "family": "reality_check",
     "text": "Rate your coordination walking through a revolving door", "spice": 2, "locality": 1, "quality_score": 8},
    # HIGHER SPICE
    {"id": "reality_check_new_36", "game": "REALITY_CHECK", "family": "reality_check",
     "text": "Rate how smoothly your pickup lines actually land according to the recipient", "spice": 4, "locality": 1, "quality_score": 9},
    {"id": "reality_check_new_37", "game": "REALITY_CHECK", "family": "reality_check",
     "text": "Rate how convincingly you fake interest in your coworker's weekend story", "spice": 3, "locality": 1, "quality_score": 9},
    {"id": "reality_check_new_38", "game": "REALITY_CHECK", "family": "reality_check",
     "text": "Rate your ability to not drunk text your ex after 2am", "spice": 5, "locality": 1, "quality_score": 9},
    {"id": "reality_check_new_39", "game": "REALITY_CHECK", "family": "reality_check",
     "text": "Rate how long you can maintain eye contact without getting weird", "spice": 3, "locality": 1, "quality_score": 8},
    {"id": "reality_check_new_40", "game": "REALITY_CHECK", "family": "reality_check",
     "text": "Rate your ability to pretend you remember someone's name when you definitely forgot", "spice": 3, "locality": 1, "quality_score": 9},
    # FINAL BATCH
    {"id": "reality_check_new_41", "game": "REALITY_CHECK", "family": "reality_check",
     "text": "Rate how often you 'just grab one thing' at Target and actually leave with one thing", "spice": 2, "locality": 1, "quality_score": 9},
    {"id": "reality_check_new_42", "game": "REALITY_CHECK", "family": "reality_check",
     "text": "Rate your ability to sing the right lyrics instead of confident nonsense", "spice": 2, "locality": 1, "quality_score": 8},
    {"id": "reality_check_new_43", "game": "REALITY_CHECK", "family": "reality_check",
     "text": "Rate how gracefully you'd handle finding out you've had spinach in your teeth all day", "spice": 2, "locality": 1, "quality_score": 8},
    {"id": "reality_check_new_44", "game": "REALITY_CHECK", "family": "reality_check",
     "text": "Rate your ability to say 'you too' only when it makes sense", "spice": 2, "locality": 1, "quality_score": 9},
    {"id": "reality_check_new_45", "game": "REALITY_CHECK", "family": "reality_check",
     "text": "Rate how well your 'professional email voice' hides your true feelings", "spice": 3, "locality": 1, "quality_score": 8},
    {"id": "reality_check_new_46", "game": "REALITY_CHECK", "family": "reality_check",
     "text": "Rate your ability to not overshare when someone asks 'how are you?'", "spice": 3, "locality": 1, "quality_score": 9},
    {"id": "reality_check_new_47", "game": "REALITY_CHECK", "family": "reality_check",
     "text": "Rate how well you'd do explaining TikTok trends to your parents", "spice": 2, "locality": 1, "quality_score": 8},
    {"id": "reality_check_new_48", "game": "REALITY_CHECK", "family": "reality_check",
     "text": "Rate your ability to assemble IKEA furniture without a relationship-ending argument", "spice": 3, "locality": 1, "quality_score": 9},
    {"id": "reality_check_new_49", "game": "REALITY_CHECK", "family": "reality_check",
     "text": "Rate how often your 'one glass of wine' stays at one glass", "spice": 3, "locality": 1, "quality_score": 8},
    {"id": "reality_check_new_50", "game": "REALITY_CHECK", "family": "reality_check",
     "text": "Rate your ability to remember where you parked without wandering the lot for 10 minutes", "spice": 2, "locality": 1, "quality_score": 8},
]

# ============================================================================
# OVER/UNDER - Complete rewrite needed (current cards are boring small talk)
# Principle: Verifiable + Personal/Embarrassing + Surprising answers
# ============================================================================

OVER_UNDER_CARDS = [
    # DIGITAL SHAME
    {"id": "over_under_new_1", "game": "OVER_UNDER", "family": "over_under",
     "text": "Number of unread emails in their inbox right now", "spice": 2, "locality": 1, "quality_score": 9},
    {"id": "over_under_new_2", "game": "OVER_UNDER", "family": "over_under",
     "text": "Number of tabs open on their phone's browser right now", "spice": 2, "locality": 1, "quality_score": 9},
    {"id": "over_under_new_3", "game": "OVER_UNDER", "family": "over_under",
     "text": "Number of times they've Googled themselves in the past month", "spice": 3, "locality": 1, "quality_score": 9},
    {"id": "over_under_new_4", "game": "OVER_UNDER", "family": "over_under",
     "text": "Number of people they follow on Instagram who have no idea who they are", "spice": 3, "locality": 1, "quality_score": 9},
    {"id": "over_under_new_5", "game": "OVER_UNDER", "family": "over_under",
     "text": "Hours of screen time they had yesterday", "spice": 2, "locality": 1, "quality_score": 8},
    {"id": "over_under_new_6", "game": "OVER_UNDER", "family": "over_under",
     "text": "Number of unlistened voicemails on their phone", "spice": 2, "locality": 1, "quality_score": 8},
    {"id": "over_under_new_7", "game": "OVER_UNDER", "family": "over_under",
     "text": "Number of times they've drafted a text and deleted it this week", "spice": 3, "locality": 1, "quality_score": 9},
    {"id": "over_under_new_8", "game": "OVER_UNDER", "family": "over_under",
     "text": "Number of dating app matches they've never messaged", "spice": 4, "locality": 1, "quality_score": 9},
    {"id": "over_under_new_9", "game": "OVER_UNDER", "family": "over_under",
     "text": "Number of passwords they've forgotten this year", "spice": 2, "locality": 1, "quality_score": 8},
    {"id": "over_under_new_10", "game": "OVER_UNDER", "family": "over_under",
     "text": "Number of times they've accidentally liked an old Instagram post while stalking someone", "spice": 4, "locality": 1, "quality_score": 9},
    # SECRET BEHAVIORS
    {"id": "over_under_new_11", "game": "OVER_UNDER", "family": "over_under",
     "text": "Number of times they've cried at a movie in the past year", "spice": 2, "locality": 1, "quality_score": 8},
    {"id": "over_under_new_12", "game": "OVER_UNDER", "family": "over_under",
     "text": "Number of days since they last washed their jeans", "spice": 3, "locality": 1, "quality_score": 9},
    {"id": "over_under_new_13", "game": "OVER_UNDER", "family": "over_under",
     "text": "Number of times they've eaten something questionable from the fridge this month", "spice": 2, "locality": 1, "quality_score": 8},
    {"id": "over_under_new_14", "game": "OVER_UNDER", "family": "over_under",
     "text": "Number of outfits they tried on before leaving the house today", "spice": 2, "locality": 1, "quality_score": 8},
    {"id": "over_under_new_15", "game": "OVER_UNDER", "family": "over_under",
     "text": "Number of times they've pretended to work while actually scrolling their phone", "spice": 3, "locality": 1, "quality_score": 9},
    {"id": "over_under_new_16", "game": "OVER_UNDER", "family": "over_under",
     "text": "Number of items in their online shopping cart they'll never actually buy", "spice": 2, "locality": 1, "quality_score": 8},
    {"id": "over_under_new_17", "game": "OVER_UNDER", "family": "over_under",
     "text": "Number of plants they've accidentally killed", "spice": 2, "locality": 1, "quality_score": 8},
    {"id": "over_under_new_18", "game": "OVER_UNDER", "family": "over_under",
     "text": "Number of times they've snoozed their alarm this morning", "spice": 2, "locality": 1, "quality_score": 8},
    # EFFORT REVEALS
    {"id": "over_under_new_19", "game": "OVER_UNDER", "family": "over_under",
     "text": "Number of gym memberships they've paid for but never used", "spice": 3, "locality": 1, "quality_score": 9},
    {"id": "over_under_new_20", "game": "OVER_UNDER", "family": "over_under",
     "text": "Number of books they've started but never finished this year", "spice": 2, "locality": 1, "quality_score": 8},
    {"id": "over_under_new_21", "game": "OVER_UNDER", "family": "over_under",
     "text": "Number of times they've rewatched their favorite comfort show", "spice": 2, "locality": 1, "quality_score": 8},
    {"id": "over_under_new_22", "game": "OVER_UNDER", "family": "over_under",
     "text": "Number of minutes they spend picking what to watch vs actually watching something", "spice": 2, "locality": 1, "quality_score": 9},
    {"id": "over_under_new_23", "game": "OVER_UNDER", "family": "over_under",
     "text": "Number of subscriptions they're paying for right now", "spice": 2, "locality": 1, "quality_score": 8},
    {"id": "over_under_new_24", "game": "OVER_UNDER", "family": "over_under",
     "text": "Number of side projects they've abandoned", "spice": 2, "locality": 1, "quality_score": 8},
    # RELATIONSHIP/SOCIAL
    {"id": "over_under_new_25", "game": "OVER_UNDER", "family": "over_under",
     "text": "Number of exes they're still friends with on social media", "spice": 4, "locality": 1, "quality_score": 9},
    {"id": "over_under_new_26", "game": "OVER_UNDER", "family": "over_under",
     "text": "Number of wedding invitations they've declined with a fake excuse", "spice": 3, "locality": 1, "quality_score": 9},
    {"id": "over_under_new_27", "game": "OVER_UNDER", "family": "over_under",
     "text": "Number of group chats they've muted forever", "spice": 3, "locality": 1, "quality_score": 9},
    {"id": "over_under_new_28", "game": "OVER_UNDER", "family": "over_under",
     "text": "Number of times they've ghosted someone in the past year", "spice": 4, "locality": 1, "quality_score": 9},
    {"id": "over_under_new_29", "game": "OVER_UNDER", "family": "over_under",
     "text": "Number of events they've said 'maybe' to knowing they'd never go", "spice": 3, "locality": 1, "quality_score": 9},
    {"id": "over_under_new_30", "game": "OVER_UNDER", "family": "over_under",
     "text": "Number of times they've rehearsed a conversation in the shower", "spice": 2, "locality": 1, "quality_score": 8},
    # EMBARRASSING SPECIFICS
    {"id": "over_under_new_31", "game": "OVER_UNDER", "family": "over_under",
     "text": "Number of photos they took to get one 'casual' selfie", "spice": 2, "locality": 1, "quality_score": 9},
    {"id": "over_under_new_32", "game": "OVER_UNDER", "family": "over_under",
     "text": "Number of times they've waved back at someone who wasn't waving at them", "spice": 2, "locality": 1, "quality_score": 9},
    {"id": "over_under_new_33", "game": "OVER_UNDER", "family": "over_under",
     "text": "Number of times they've said 'you too' to a waiter who said 'enjoy your meal'", "spice": 2, "locality": 1, "quality_score": 9},
    {"id": "over_under_new_34", "game": "OVER_UNDER", "family": "over_under",
     "text": "Number of Tupperware containers in their fridge they're afraid to open", "spice": 2, "locality": 1, "quality_score": 9},
    {"id": "over_under_new_35", "game": "OVER_UNDER", "family": "over_under",
     "text": "Number of times they've pretended their phone was ringing to escape a conversation", "spice": 3, "locality": 1, "quality_score": 9},
    # HIGHER SPICE
    {"id": "over_under_new_36", "game": "OVER_UNDER", "family": "over_under",
     "text": "Number of times they've hate-followed someone on social media", "spice": 3, "locality": 1, "quality_score": 9},
    {"id": "over_under_new_37", "game": "OVER_UNDER", "family": "over_under",
     "text": "Number of lies on their dating profile", "spice": 4, "locality": 1, "quality_score": 9},
    {"id": "over_under_new_38", "game": "OVER_UNDER", "family": "over_under",
     "text": "Number of 'seen' messages they've left on read intentionally", "spice": 3, "locality": 1, "quality_score": 8},
    {"id": "over_under_new_39", "game": "OVER_UNDER", "family": "over_under",
     "text": "Number of people they've saved in their phone with a warning emoji", "spice": 4, "locality": 1, "quality_score": 9},
    {"id": "over_under_new_40", "game": "OVER_UNDER", "family": "over_under",
     "text": "Number of 'accidental' screenshots of conversations they've taken", "spice": 4, "locality": 1, "quality_score": 9},
    # FINAL BATCH - VERIFIABLE
    {"id": "over_under_new_41", "game": "OVER_UNDER", "family": "over_under",
     "text": "Number of times they check their phone per hour", "spice": 2, "locality": 1, "quality_score": 8},
    {"id": "over_under_new_42", "game": "OVER_UNDER", "family": "over_under",
     "text": "Percentage of their camera roll that's screenshots", "spice": 2, "locality": 1, "quality_score": 8},
    {"id": "over_under_new_43", "game": "OVER_UNDER", "family": "over_under",
     "text": "Number of times they've gone back inside because they forgot something", "spice": 2, "locality": 1, "quality_score": 8},
    {"id": "over_under_new_44", "game": "OVER_UNDER", "family": "over_under",
     "text": "Number of unfinished drinks in their car right now", "spice": 2, "locality": 1, "quality_score": 8},
    {"id": "over_under_new_45", "game": "OVER_UNDER", "family": "over_under",
     "text": "Number of gift cards they have with $2 or less remaining", "spice": 2, "locality": 1, "quality_score": 8},
    {"id": "over_under_new_46", "game": "OVER_UNDER", "family": "over_under",
     "text": "Number of apps on their phone they've opened once and never again", "spice": 2, "locality": 1, "quality_score": 8},
    {"id": "over_under_new_47", "game": "OVER_UNDER", "family": "over_under",
     "text": "Number of times they've said 'let's definitely hang out soon' and meant it", "spice": 3, "locality": 1, "quality_score": 9},
    {"id": "over_under_new_48", "game": "OVER_UNDER", "family": "over_under",
     "text": "Number of times they've panic-cleaned before someone came over", "spice": 2, "locality": 1, "quality_score": 8},
    {"id": "over_under_new_49", "game": "OVER_UNDER", "family": "over_under",
     "text": "Number of things they own that still have the tag on", "spice": 2, "locality": 1, "quality_score": 8},
    {"id": "over_under_new_50", "game": "OVER_UNDER", "family": "over_under",
     "text": "Number of browser tabs they have open on their computer right now", "spice": 2, "locality": 1, "quality_score": 8},
]


# ============================================================================
# TEXT THREAD TRAP - Missing "tones" field on ALL cards + quality improvement
# Principle: High-stakes text + 4 contrasting tones for comedic mismatch
# ============================================================================

TEXT_THREAD_TRAP_CARDS = [
    # CONFRONTATION TEXTS
    {"id": "text_trap_new_1", "game": "TEXT_THREAD_TRAP", "family": "text_thread_trap",
     "text": "Your ex texts: 'I still have your Netflix password. Should I keep using it? 👀'",
     "tones": ["Flirty", "Cold", "Petty", "Professional"], "spice": 4, "locality": 1, "quality_score": 9},
    {"id": "text_trap_new_2", "game": "TEXT_THREAD_TRAP", "family": "text_thread_trap",
     "text": "Your boss texts: 'Saw you at Target when you called in sick yesterday. Interesting.'",
     "tones": ["Panicked", "Gaslighting", "Professional", "Unhinged"], "spice": 4, "locality": 1, "quality_score": 9},
    {"id": "text_trap_new_3", "game": "TEXT_THREAD_TRAP", "family": "text_thread_trap",
     "text": "Your mom texts: 'We need to talk about what the Ring doorbell recorded last night.'",
     "tones": ["Wholesome", "Cryptic", "Panicked", "Defensive"], "spice": 4, "locality": 1, "quality_score": 9},
    {"id": "text_trap_new_4", "game": "TEXT_THREAD_TRAP", "family": "text_thread_trap",
     "text": "Unknown number: 'I know what you did at the company party. We should discuss.'",
     "tones": ["Confused", "Chaotic", "Professional", "Flirty"], "spice": 5, "locality": 1, "quality_score": 9},
    {"id": "text_trap_new_5", "game": "TEXT_THREAD_TRAP", "family": "text_thread_trap",
     "text": "Your friend texts: 'Why did everyone in the group chat suddenly go quiet when you joined?'",
     "tones": ["Unbothered", "Paranoid", "Passive-Aggressive", "Wholesome"], "spice": 3, "locality": 1, "quality_score": 8},
    # AWKWARD REQUEST TEXTS
    {"id": "text_trap_new_6", "game": "TEXT_THREAD_TRAP", "family": "text_thread_trap",
     "text": "Your landlord texts: 'Can we talk about the noises coming from your apartment at 3am?'",
     "tones": ["Innocent", "Flirty", "Defensive", "Unhinged"], "spice": 4, "locality": 1, "quality_score": 9},
    {"id": "text_trap_new_7", "game": "TEXT_THREAD_TRAP", "family": "text_thread_trap",
     "text": "A coworker texts: 'Can you cover my shift? I know you hate me but it's an emergency.'",
     "tones": ["Petty", "Overly Enthusiastic", "Cold", "Chaotic"], "spice": 3, "locality": 1, "quality_score": 8},
    {"id": "text_trap_new_8", "game": "TEXT_THREAD_TRAP", "family": "text_thread_trap",
     "text": "Your friend's ex texts YOU: 'Can you tell [friend] I need to talk to them? They blocked me.'",
     "tones": ["Loyal", "Cryptic", "Messy", "Professional"], "spice": 4, "locality": 1, "quality_score": 9},
    {"id": "text_trap_new_9", "game": "TEXT_THREAD_TRAP", "family": "text_thread_trap",
     "text": "Your ex's mom texts: 'I just want you to know I always liked you more than them.'",
     "tones": ["Awkward", "Flattered", "Boundaries", "Chaotic"], "spice": 4, "locality": 1, "quality_score": 9},
    {"id": "text_trap_new_10", "game": "TEXT_THREAD_TRAP", "family": "text_thread_trap",
     "text": "Someone you ghosted texts: 'I saw you like my photo. So you're alive?'",
     "tones": ["Gaslighting", "Apologetic", "Unbothered", "Flirty"], "spice": 4, "locality": 1, "quality_score": 9},
    # RELATIONSHIP BOMBS
    {"id": "text_trap_new_11", "game": "TEXT_THREAD_TRAP", "family": "text_thread_trap",
     "text": "Your partner texts: 'Who's the person you were tagged with in that photo from 2019?'",
     "tones": ["Calm", "Panicked", "Gaslighting", "Confused"], "spice": 4, "locality": 1, "quality_score": 9},
    {"id": "text_trap_new_12", "game": "TEXT_THREAD_TRAP", "family": "text_thread_trap",
     "text": "Your crush texts: 'Do you want to grab coffee? As friends, obviously.'",
     "tones": ["Hopeful", "Devastated", "Cool", "Unhinged"], "spice": 3, "locality": 1, "quality_score": 8},
    {"id": "text_trap_new_13", "game": "TEXT_THREAD_TRAP", "family": "text_thread_trap",
     "text": "Your ex texts: 'I had a dream about you last night. Anyway, how's your mom?'",
     "tones": ["Curious", "Boundaries", "Messy", "Cryptic"], "spice": 4, "locality": 1, "quality_score": 9},
    {"id": "text_trap_new_14", "game": "TEXT_THREAD_TRAP", "family": "text_thread_trap",
     "text": "Someone you went on ONE date with texts: 'My therapist says I should tell you how I really feel.'",
     "tones": ["Terrified", "Supportive", "Boundaries", "Chaotic"], "spice": 4, "locality": 1, "quality_score": 9},
    {"id": "text_trap_new_15", "game": "TEXT_THREAD_TRAP", "family": "text_thread_trap",
     "text": "Your situationship texts: 'So what are we?'",
     "tones": ["Evasive", "Honest", "Chaotic", "Philosophical"], "spice": 4, "locality": 1, "quality_score": 9},
    # FAMILY CHAOS
    {"id": "text_trap_new_16", "game": "TEXT_THREAD_TRAP", "family": "text_thread_trap",
     "text": "Your dad texts: 'Your aunt saw your TikTok. We need to have a conversation.'",
     "tones": ["Confused", "Defensive", "Proud", "Panicked"], "spice": 3, "locality": 1, "quality_score": 8},
    {"id": "text_trap_new_17", "game": "TEXT_THREAD_TRAP", "family": "text_thread_trap",
     "text": "Family group chat: 'We voted and Thanksgiving is at YOUR place this year.'",
     "tones": ["Gracious", "Chaotic", "Negotiating", "Unhinged"], "spice": 2, "locality": 1, "quality_score": 8},
    {"id": "text_trap_new_18", "game": "TEXT_THREAD_TRAP", "family": "text_thread_trap",
     "text": "Your sibling texts: 'Mom and Dad are getting a divorce. Also can you Venmo me $50?'",
     "tones": ["Supportive", "Boundaries", "Chaotic", "Petty"], "spice": 4, "locality": 1, "quality_score": 9},
    {"id": "text_trap_new_19", "game": "TEXT_THREAD_TRAP", "family": "text_thread_trap",
     "text": "Your grandma texts: 'What does 'Netflix and chill' mean? Your cousin won't tell me.'",
     "tones": ["Honest", "Evasive", "Educational", "Chaotic"], "spice": 3, "locality": 1, "quality_score": 9},
    {"id": "text_trap_new_20", "game": "TEXT_THREAD_TRAP", "family": "text_thread_trap",
     "text": "Your parent texts: 'Found your journal from high school. Very interesting.'",
     "tones": ["Panicked", "Unbothered", "Defensive", "Cryptic"], "spice": 3, "locality": 1, "quality_score": 8},
    # PROFESSIONAL DISASTERS
    {"id": "text_trap_new_21", "game": "TEXT_THREAD_TRAP", "family": "text_thread_trap",
     "text": "HR texts: 'Can you come to my office first thing Monday? Bring your laptop.'",
     "tones": ["Panicked", "Confident", "Chaotic", "Professional"], "spice": 3, "locality": 1, "quality_score": 8},
    {"id": "text_trap_new_22", "game": "TEXT_THREAD_TRAP", "family": "text_thread_trap",
     "text": "Your coworker texts: 'Did you mean to reply-all with that email?'",
     "tones": ["Panicked", "Unbothered", "Confused", "Chaotic"], "spice": 4, "locality": 1, "quality_score": 9},
    {"id": "text_trap_new_23", "game": "TEXT_THREAD_TRAP", "family": "text_thread_trap",
     "text": "Your boss texts: 'I need to talk to you about the company card charges.'",
     "tones": ["Confident", "Panicked", "Gaslighting", "Professional"], "spice": 4, "locality": 1, "quality_score": 9},
    {"id": "text_trap_new_24", "game": "TEXT_THREAD_TRAP", "family": "text_thread_trap",
     "text": "A LinkedIn connection texts your personal number: 'Saw you viewed my profile 8 times. Coffee?'",
     "tones": ["Caught", "Professional", "Flirty", "Boundaries"], "spice": 3, "locality": 1, "quality_score": 9},
    {"id": "text_trap_new_25", "game": "TEXT_THREAD_TRAP", "family": "text_thread_trap",
     "text": "Your coworker you gossip with texts: 'I think [person you gossiped about] saw our chat.'",
     "tones": ["Panicked", "Unbothered", "Damage Control", "Chaotic"], "spice": 4, "locality": 1, "quality_score": 9},
    # SOCIAL CHAOS
    {"id": "text_trap_new_26", "game": "TEXT_THREAD_TRAP", "family": "text_thread_trap",
     "text": "Group chat: 'Why did you leave the party without saying goodbye?'",
     "tones": ["Apologetic", "Chaotic", "Mysterious", "Boundaries"], "spice": 2, "locality": 1, "quality_score": 8},
    {"id": "text_trap_new_27", "game": "TEXT_THREAD_TRAP", "family": "text_thread_trap",
     "text": "Your friend texts: 'Did you tell [mutual friend] my secret? They just texted me about it.'",
     "tones": ["Innocent", "Guilty", "Deflecting", "Chaotic"], "spice": 3, "locality": 1, "quality_score": 9},
    {"id": "text_trap_new_28", "game": "TEXT_THREAD_TRAP", "family": "text_thread_trap",
     "text": "A friend texts: 'I saw you at the mall today but you looked busy. With who though?'",
     "tones": ["Confused", "Evasive", "Chaotic", "Honest"], "spice": 3, "locality": 1, "quality_score": 8},
    {"id": "text_trap_new_29", "game": "TEXT_THREAD_TRAP", "family": "text_thread_trap",
     "text": "Someone you met once texts: 'I'm in your area! Can I crash at your place tonight?'",
     "tones": ["Boundaries", "Panicked", "Chaotic", "Overly Welcoming"], "spice": 3, "locality": 1, "quality_score": 9},
    {"id": "text_trap_new_30", "game": "TEXT_THREAD_TRAP", "family": "text_thread_trap",
     "text": "Your friend texts: 'Why are you hanging out with [person they hate] without telling me?'",
     "tones": ["Defensive", "Apologetic", "Unbothered", "Chaotic"], "spice": 3, "locality": 1, "quality_score": 8},
    # HIGHER SPICE
    {"id": "text_trap_new_31", "game": "TEXT_THREAD_TRAP", "family": "text_thread_trap",
     "text": "Your ex texts: 'Your current partner just added me on Instagram. Should I accept?'",
     "tones": ["Panicked", "Boundaries", "Chaotic", "Petty"], "spice": 5, "locality": 1, "quality_score": 9},
    {"id": "text_trap_new_32", "game": "TEXT_THREAD_TRAP", "family": "text_thread_trap",
     "text": "A random number texts: 'Stop texting my partner. This is your only warning.'",
     "tones": ["Confused", "Apologetic", "Chaotic", "Petty"], "spice": 5, "locality": 1, "quality_score": 9},
    {"id": "text_trap_new_33", "game": "TEXT_THREAD_TRAP", "family": "text_thread_trap",
     "text": "Your one night stand texts: 'I'm late. Not late to something. Just... late.'",
     "tones": ["Supportive", "Panicked", "Ghosting", "Chaotic"], "spice": 5, "locality": 1, "quality_score": 9},
    {"id": "text_trap_new_34", "game": "TEXT_THREAD_TRAP", "family": "text_thread_trap",
     "text": "Your ex texts: 'I wrote you a song. Can I perform it at your birthday party?'",
     "tones": ["Flattered", "Terrified", "Boundaries", "Chaotic"], "spice": 4, "locality": 1, "quality_score": 9},
    {"id": "text_trap_new_35", "game": "TEXT_THREAD_TRAP", "family": "text_thread_trap",
     "text": "Someone you're avoiding texts: 'I can see you typing and stopping. Just say it.'",
     "tones": ["Caught", "Gaslighting", "Honest", "Chaotic"], "spice": 4, "locality": 1, "quality_score": 9},
    # WILD CARDS
    {"id": "text_trap_new_36", "game": "TEXT_THREAD_TRAP", "family": "text_thread_trap",
     "text": "Your Uber driver from last night texts from their personal phone: 'You left something in my car. Want to meet up?'",
     "tones": ["Grateful", "Suspicious", "Boundaries", "Chaotic"], "spice": 4, "locality": 1, "quality_score": 9},
    {"id": "text_trap_new_37", "game": "TEXT_THREAD_TRAP", "family": "text_thread_trap",
     "text": "A number you don't recognize texts: 'Hey, it's [ex's new partner]. Can we talk?'",
     "tones": ["Curious", "Boundaries", "Petty", "Chaotic"], "spice": 4, "locality": 1, "quality_score": 9},
    {"id": "text_trap_new_38", "game": "TEXT_THREAD_TRAP", "family": "text_thread_trap",
     "text": "Your friend texts: 'I'm outside your house. I know you're home. Let me in.'",
     "tones": ["Welcoming", "Terrified", "Boundaries", "Chaotic"], "spice": 3, "locality": 1, "quality_score": 8},
    {"id": "text_trap_new_39", "game": "TEXT_THREAD_TRAP", "family": "text_thread_trap",
     "text": "Wrong number texts: 'The package is in the usual spot. Don't be late this time.'",
     "tones": ["Confused", "Intrigued", "Report It", "Chaotic"], "spice": 3, "locality": 1, "quality_score": 8},
    {"id": "text_trap_new_40", "game": "TEXT_THREAD_TRAP", "family": "text_thread_trap",
     "text": "Your dentist's personal number: 'I've been thinking about your teeth. Coffee?'",
     "tones": ["Confused", "Flattered", "Concerned", "Chaotic"], "spice": 4, "locality": 1, "quality_score": 9},
    # LOWER SPICE OPTIONS
    {"id": "text_trap_new_41", "game": "TEXT_THREAD_TRAP", "family": "text_thread_trap",
     "text": "Your friend texts: 'I know it's 2am but I need to vent about my day. You up?'",
     "tones": ["Supportive", "Boundaries", "Asleep", "Chaotic"], "spice": 2, "locality": 1, "quality_score": 8},
    {"id": "text_trap_new_42", "game": "TEXT_THREAD_TRAP", "family": "text_thread_trap",
     "text": "Group chat: 'We're splitting the bill evenly but you only had a salad. Thoughts?'",
     "tones": ["Gracious", "Petty", "Negotiating", "Chaotic"], "spice": 2, "locality": 1, "quality_score": 8},
    {"id": "text_trap_new_43", "game": "TEXT_THREAD_TRAP", "family": "text_thread_trap",
     "text": "Your friend texts: 'Be honest, did you actually read my manuscript or just skim it?'",
     "tones": ["Supportive", "Caught", "Deflecting", "Honest"], "spice": 2, "locality": 1, "quality_score": 8},
    {"id": "text_trap_new_44", "game": "TEXT_THREAD_TRAP", "family": "text_thread_trap",
     "text": "Group chat: 'Who ate my clearly labeled lunch from the fridge? I know it was one of you.'",
     "tones": ["Innocent", "Guilty", "Chaotic", "Deflecting"], "spice": 2, "locality": 1, "quality_score": 8},
    {"id": "text_trap_new_45", "game": "TEXT_THREAD_TRAP", "family": "text_thread_trap",
     "text": "Your neighbor texts: 'Can we talk about the noise last night? I have questions.'",
     "tones": ["Apologetic", "Confused", "Chaotic", "Defensive"], "spice": 3, "locality": 1, "quality_score": 8},
    {"id": "text_trap_new_46", "game": "TEXT_THREAD_TRAP", "family": "text_thread_trap",
     "text": "Your friend texts a photo of you from 10 years ago: 'Should I post this throwback?'",
     "tones": ["Threatening", "Begging", "Chaotic", "Unbothered"], "spice": 2, "locality": 1, "quality_score": 8},
    {"id": "text_trap_new_47", "game": "TEXT_THREAD_TRAP", "family": "text_thread_trap",
     "text": "Your mom texts: 'Why did you unfollow your cousin? She's very hurt.'",
     "tones": ["Defensive", "Petty", "Diplomatic", "Chaotic"], "spice": 2, "locality": 1, "quality_score": 8},
    {"id": "text_trap_new_48", "game": "TEXT_THREAD_TRAP", "family": "text_thread_trap",
     "text": "Someone from high school texts: 'Hey! Remember me? I have an exciting business opportunity!'",
     "tones": ["Suspicious", "Polite Decline", "Chaotic", "Interested"], "spice": 2, "locality": 1, "quality_score": 9},
    {"id": "text_trap_new_49", "game": "TEXT_THREAD_TRAP", "family": "text_thread_trap",
     "text": "Your friend texts: 'I just told my therapist about you. She has some thoughts.'",
     "tones": ["Curious", "Offended", "Supportive", "Chaotic"], "spice": 3, "locality": 1, "quality_score": 9},
    {"id": "text_trap_new_50", "game": "TEXT_THREAD_TRAP", "family": "text_thread_trap",
     "text": "Group chat: 'Everyone bring a plus one to the dinner. No pressure but also yes pressure.'",
     "tones": ["Panicked", "Confident", "Chaotic", "Negotiating"], "spice": 3, "locality": 1, "quality_score": 8},
]


# ============================================================================
# POISON PITCH (Would You Rather) - Partial rewrite - remove clichés, add absurdity
# Principle: Visual imagery + genuine dilemmas + takes 5+ seconds to answer
# ============================================================================

POISON_PITCH_CARDS = [
    # BODY HORROR ABSURDITY
    {"id": "poison_pitch_new_1", "game": "POISON_PITCH", "family": "poison_pitch",
     "text": "Would you rather...", 
     "optionA": "sweat maple syrup for the rest of your life",
     "optionB": "cry orange Fanta every time you're sad",
     "spice": 3, "locality": 1, "quality_score": 10},
    {"id": "poison_pitch_new_2", "game": "POISON_PITCH", "family": "poison_pitch",
     "text": "Would you rather...",
     "optionA": "have breath that permanently smells like a Subway restaurant",
     "optionB": "have armpits that honk like a goose when you raise your arms",
     "spice": 3, "locality": 1, "quality_score": 10},
    {"id": "poison_pitch_new_3", "game": "POISON_PITCH", "family": "poison_pitch",
     "text": "Would you rather...",
     "optionA": "sneeze glitter for the rest of your life",
     "optionB": "hiccup the first 3 notes of 'Happy Birthday' forever",
     "spice": 2, "locality": 1, "quality_score": 9},
    {"id": "poison_pitch_new_4", "game": "POISON_PITCH", "family": "poison_pitch",
     "text": "Would you rather...",
     "optionA": "have your internal monologue broadcast on a speaker above your head",
     "optionB": "have everyone see your browser history from the past 24 hours",
     "spice": 4, "locality": 1, "quality_score": 10},
    {"id": "poison_pitch_new_5", "game": "POISON_PITCH", "family": "poison_pitch",
     "text": "Would you rather...",
     "optionA": "have taste buds in your armpits",
     "optionB": "have smell receptors on the bottom of your feet",
     "spice": 4, "locality": 1, "quality_score": 9},
    # SOCIAL NIGHTMARES
    {"id": "poison_pitch_new_6", "game": "POISON_PITCH", "family": "poison_pitch",
     "text": "Would you rather...",
     "optionA": "every ex you've ever had attends your wedding",
     "optionB": "your entire search history is read aloud at your funeral",
     "spice": 5, "locality": 1, "quality_score": 10},
    {"id": "poison_pitch_new_7", "game": "POISON_PITCH", "family": "poison_pitch",
     "text": "Would you rather...",
     "optionA": "your parents read every text you've ever sent",
     "optionB": "your boss sees every photo in your camera roll",
     "spice": 5, "locality": 1, "quality_score": 9},
    {"id": "poison_pitch_new_8", "game": "POISON_PITCH", "family": "poison_pitch",
     "text": "Would you rather...",
     "optionA": "say everything you think out loud for a week",
     "optionB": "have everyone say what they really think about you for a day",
     "spice": 4, "locality": 1, "quality_score": 9},
    {"id": "poison_pitch_new_9", "game": "POISON_PITCH", "family": "poison_pitch",
     "text": "Would you rather...",
     "optionA": "your embarrassing moments are turned into a Super Bowl commercial",
     "optionB": "your most private journal entries become a best-selling audiobook read by Morgan Freeman",
     "spice": 4, "locality": 1, "quality_score": 10},
    {"id": "poison_pitch_new_10", "game": "POISON_PITCH", "family": "poison_pitch",
     "text": "Would you rather...",
     "optionA": "relive your most embarrassing moment every year on your birthday",
     "optionB": "have a live studio audience react to your daily life",
     "spice": 3, "locality": 1, "quality_score": 9},
    # LIFESTYLE TRADE-OFFS
    {"id": "poison_pitch_new_11", "game": "POISON_PITCH", "family": "poison_pitch",
     "text": "Would you rather...",
     "optionA": "only be able to communicate through corporate email language",
     "optionB": "only be able to communicate through 2009 MySpace messages (caps, emoticons, random letters)",
     "spice": 2, "locality": 1, "quality_score": 9},
    {"id": "poison_pitch_new_12", "game": "POISON_PITCH", "family": "poison_pitch",
     "text": "Would you rather...",
     "optionA": "every song you hear is replaced with a Kidz Bop version",
     "optionB": "every movie you watch has laugh track added to every scene",
     "spice": 2, "locality": 1, "quality_score": 9},
    {"id": "poison_pitch_new_13", "game": "POISON_PITCH", "family": "poison_pitch",
     "text": "Would you rather...",
     "optionA": "only be able to sleep in hotel rooms for the rest of your life",
     "optionB": "only be able to eat at airport restaurants forever",
     "spice": 2, "locality": 1, "quality_score": 8},
    {"id": "poison_pitch_new_14", "game": "POISON_PITCH", "family": "poison_pitch",
     "text": "Would you rather...",
     "optionA": "your only outfit is whatever you wore to prom",
     "optionB": "your only hairstyle is whatever you had in 7th grade",
     "spice": 2, "locality": 1, "quality_score": 9},
    {"id": "poison_pitch_new_15", "game": "POISON_PITCH", "family": "poison_pitch",
     "text": "Would you rather...",
     "optionA": "live in a world where everyone can see your Spotify listening history at all times",
     "optionB": "live in a world where everyone can see how long you spend on each app daily",
     "spice": 3, "locality": 1, "quality_score": 9},
    # ABSURD SCENARIOS
    {"id": "poison_pitch_new_16", "game": "POISON_PITCH", "family": "poison_pitch",
     "text": "Would you rather...",
     "optionA": "fight one horse-sized duck in a Denny's parking lot at 2am",
     "optionB": "fight 100 duck-sized horses that know your home address",
     "spice": 3, "locality": 1, "quality_score": 10},
    {"id": "poison_pitch_new_17", "game": "POISON_PITCH", "family": "poison_pitch",
     "text": "Would you rather...",
     "optionA": "have fingers as long as your legs",
     "optionB": "have legs as long as your fingers",
     "spice": 3, "locality": 1, "quality_score": 9},
    {"id": "poison_pitch_new_18", "game": "POISON_PITCH", "family": "poison_pitch",
     "text": "Would you rather...",
     "optionA": "your pet could talk but only criticizes your life choices",
     "optionB": "your plants could talk but only guilt you for not watering them",
     "spice": 2, "locality": 1, "quality_score": 9},
    {"id": "poison_pitch_new_19", "game": "POISON_PITCH", "family": "poison_pitch",
     "text": "Would you rather...",
     "optionA": "have to narrate your life out loud like a nature documentary",
     "optionB": "have dramatic orchestral music play based on your emotions that everyone can hear",
     "spice": 2, "locality": 1, "quality_score": 9},
    {"id": "poison_pitch_new_20", "game": "POISON_PITCH", "family": "poison_pitch",
     "text": "Would you rather...",
     "optionA": "be haunted by a ghost that just makes passive-aggressive comments",
     "optionB": "have a guardian angel that's really bad at their job",
     "spice": 2, "locality": 1, "quality_score": 9},
    # RELATIONSHIP CHAOS
    {"id": "poison_pitch_new_21", "game": "POISON_PITCH", "family": "poison_pitch",
     "text": "Would you rather...",
     "optionA": "your partner can read your mind but only the critical thoughts",
     "optionB": "you can read their mind but only the thoughts about their ex",
     "spice": 5, "locality": 1, "quality_score": 9},
    {"id": "poison_pitch_new_22", "game": "POISON_PITCH", "family": "poison_pitch",
     "text": "Would you rather...",
     "optionA": "date someone who's perfect but their family despises you forever",
     "optionB": "date someone who's okay but their family thinks you're the best thing that ever happened",
     "spice": 3, "locality": 1, "quality_score": 9},
    {"id": "poison_pitch_new_23", "game": "POISON_PITCH", "family": "poison_pitch",
     "text": "Would you rather...",
     "optionA": "always know when someone is lying to you but never be able to call it out",
     "optionB": "never be able to lie but have no control over when you blurt out the truth",
     "spice": 3, "locality": 1, "quality_score": 9},
    {"id": "poison_pitch_new_24", "game": "POISON_PITCH", "family": "poison_pitch",
     "text": "Would you rather...",
     "optionA": "your ex becomes your boss",
     "optionB": "your boss becomes your in-law",
     "spice": 4, "locality": 1, "quality_score": 9},
    {"id": "poison_pitch_new_25", "game": "POISON_PITCH", "family": "poison_pitch",
     "text": "Would you rather...",
     "optionA": "have your mom as your wingwoman at every bar",
     "optionB": "have your dad give 'the talk' to every person you date on the first date",
     "spice": 4, "locality": 1, "quality_score": 9},
    # MODERN LIFE DILEMMAS
    {"id": "poison_pitch_new_26", "game": "POISON_PITCH", "family": "poison_pitch",
     "text": "Would you rather...",
     "optionA": "your phone autocorrects everything to sound extremely formal",
     "optionB": "your phone autocorrects everything to sound extremely horny",
     "spice": 4, "locality": 1, "quality_score": 9},
    {"id": "poison_pitch_new_27", "game": "POISON_PITCH", "family": "poison_pitch",
     "text": "Would you rather...",
     "optionA": "give up caffeine forever",
     "optionB": "give up the ability to scroll",
     "spice": 2, "locality": 1, "quality_score": 8},
    {"id": "poison_pitch_new_28", "game": "POISON_PITCH", "family": "poison_pitch",
     "text": "Would you rather...",
     "optionA": "your Spotify Wrapped is projected on a billboard in your hometown",
     "optionB": "your Screen Time report is sent to everyone in your contacts weekly",
     "spice": 3, "locality": 1, "quality_score": 9},
    {"id": "poison_pitch_new_29", "game": "POISON_PITCH", "family": "poison_pitch",
     "text": "Would you rather...",
     "optionA": "only be able to charge your phone at a Starbucks while ordering something",
     "optionB": "your WiFi password is your most embarrassing secret",
     "spice": 3, "locality": 1, "quality_score": 8},
    {"id": "poison_pitch_new_30", "game": "POISON_PITCH", "family": "poison_pitch",
     "text": "Would you rather...",
     "optionA": "every email you send has your high school yearbook photo as your signature",
     "optionB": "every text you send is followed by a 30-second voice message explaining what you meant",
     "spice": 2, "locality": 1, "quality_score": 9},
    # HIGHER SPICE
    {"id": "poison_pitch_new_31", "game": "POISON_PITCH", "family": "poison_pitch",
     "text": "Would you rather...",
     "optionA": "have to loudly announce every time you're attracted to someone",
     "optionB": "have everyone you've ever been attracted to receive a notification",
     "spice": 5, "locality": 1, "quality_score": 10},
    {"id": "poison_pitch_new_32", "game": "POISON_PITCH", "family": "poison_pitch",
     "text": "Would you rather...",
     "optionA": "every lie you've ever told is written on your skin like tattoos",
     "optionB": "every mean thought you've had plays above your head like a hologram",
     "spice": 4, "locality": 1, "quality_score": 9},
    {"id": "poison_pitch_new_33", "game": "POISON_PITCH", "family": "poison_pitch",
     "text": "Would you rather...",
     "optionA": "orgasm sounds like a dial-up modem",
     "optionB": "sneeze sounds like you're saying 'harder daddy'",
     "spice": 5, "locality": 1, "quality_score": 9},
    {"id": "poison_pitch_new_34", "game": "POISON_PITCH", "family": "poison_pitch",
     "text": "Would you rather...",
     "optionA": "have your sex playlist become your ringtone for all calls",
     "optionB": "have your most played song be 'My Heart Will Go On' (publicly visible)",
     "spice": 5, "locality": 1, "quality_score": 9},
    {"id": "poison_pitch_new_35", "game": "POISON_PITCH", "family": "poison_pitch",
     "text": "Would you rather...",
     "optionA": "every time you're horny, an air horn goes off somewhere in your vicinity",
     "optionB": "every time you lie, you get visibly aroused",
     "spice": 5, "locality": 1, "quality_score": 9},
    # LOWER SPICE / WHOLESOME-ISH
    {"id": "poison_pitch_new_36", "game": "POISON_PITCH", "family": "poison_pitch",
     "text": "Would you rather...",
     "optionA": "always feel like you need to sneeze but never actually sneeze",
     "optionB": "have a constant itch you can never quite reach",
     "spice": 1, "locality": 1, "quality_score": 8},
    {"id": "poison_pitch_new_37", "game": "POISON_PITCH", "family": "poison_pitch",
     "text": "Would you rather...",
     "optionA": "every time you enter a room, someone announces you with an air horn",
     "optionB": "every time you leave a room, confetti falls from nowhere",
     "spice": 1, "locality": 1, "quality_score": 8},
    {"id": "poison_pitch_new_38", "game": "POISON_PITCH", "family": "poison_pitch",
     "text": "Would you rather...",
     "optionA": "have a theme song that plays every time you walk somewhere",
     "optionB": "have a narrator describe your actions out loud (David Attenborough voice)",
     "spice": 1, "locality": 1, "quality_score": 9},
    {"id": "poison_pitch_new_39", "game": "POISON_PITCH", "family": "poison_pitch",
     "text": "Would you rather...",
     "optionA": "have to eat only with chopsticks for every meal forever",
     "optionB": "have to drink everything through a silly straw forever",
     "spice": 1, "locality": 1, "quality_score": 8},
    {"id": "poison_pitch_new_40", "game": "POISON_PITCH", "family": "poison_pitch",
     "text": "Would you rather...",
     "optionA": "only be able to high-five as a greeting",
     "optionB": "only be able to bow as a greeting",
     "spice": 1, "locality": 1, "quality_score": 7},
    # MORE MEDIUM SPICE
    {"id": "poison_pitch_new_41", "game": "POISON_PITCH", "family": "poison_pitch",
     "text": "Would you rather...",
     "optionA": "have everyone see a health bar above your head",
     "optionB": "have everyone see your current mood as an emoji above your head",
     "spice": 2, "locality": 1, "quality_score": 9},
    {"id": "poison_pitch_new_42", "game": "POISON_PITCH", "family": "poison_pitch",
     "text": "Would you rather...",
     "optionA": "have your Google Maps voice be your ex reading you directions",
     "optionB": "have your alarm clock be your mom's disappointed sigh",
     "spice": 3, "locality": 1, "quality_score": 9},
    {"id": "poison_pitch_new_43", "game": "POISON_PITCH", "family": "poison_pitch",
     "text": "Would you rather...",
     "optionA": "only be able to watch movies with your parents' commentary",
     "optionB": "only be able to listen to music with a friend's unsolicited opinions",
     "spice": 2, "locality": 1, "quality_score": 8},
    {"id": "poison_pitch_new_44", "game": "POISON_PITCH", "family": "poison_pitch",
     "text": "Would you rather...",
     "optionA": "everything you cook tastes like it needs more salt but you can never add enough",
     "optionB": "everything you drink is slightly too warm forever",
     "spice": 2, "locality": 1, "quality_score": 8},
    {"id": "poison_pitch_new_45", "game": "POISON_PITCH", "family": "poison_pitch",
     "text": "Would you rather...",
     "optionA": "have to share your exact location with everyone at all times",
     "optionB": "have to share your exact step count with everyone at all times",
     "spice": 3, "locality": 1, "quality_score": 8},
    {"id": "poison_pitch_new_46", "game": "POISON_PITCH", "family": "poison_pitch",
     "text": "Would you rather...",
     "optionA": "your dreams are projected on your bedroom ceiling for anyone to see",
     "optionB": "your dreams become episodes of a podcast your friends listen to",
     "spice": 4, "locality": 1, "quality_score": 9},
    {"id": "poison_pitch_new_47", "game": "POISON_PITCH", "family": "poison_pitch",
     "text": "Would you rather...",
     "optionA": "your inner critic is Morgan Freeman narrating your failures",
     "optionB": "your inner cheerleader is Guy Fieri hyping you up",
     "spice": 2, "locality": 1, "quality_score": 9},
    {"id": "poison_pitch_new_48", "game": "POISON_PITCH", "family": "poison_pitch",
     "text": "Would you rather...",
     "optionA": "every time you make a mistake, a laugh track plays",
     "optionB": "every time you succeed, a golf clap follows you",
     "spice": 2, "locality": 1, "quality_score": 8},
    {"id": "poison_pitch_new_49", "game": "POISON_PITCH", "family": "poison_pitch",
     "text": "Would you rather...",
     "optionA": "be able to pause time but only while you're on the toilet",
     "optionB": "be able to fly but only 3 feet off the ground",
     "spice": 2, "locality": 1, "quality_score": 9},
    {"id": "poison_pitch_new_50", "game": "POISON_PITCH", "family": "poison_pitch",
     "text": "Would you rather...",
     "optionA": "have perfectly clear skin but sweat Nickelodeon slime",
     "optionB": "have perfect hair but it changes color based on your mood (visible to everyone)",
     "spice": 2, "locality": 1, "quality_score": 9},
]


# ============================================================================
# HOT SEAT IMPOSTER - Partial rewrite - make questions require ACTUAL knowledge
# Principle: Questions where generic answers don't work, imposter gets caught
# ============================================================================

HOT_SEAT_IMPOSTER_CARDS = [
    # VERIFIABLE SPECIFIC QUESTIONS
    {"id": "hot_seat_new_1", "game": "HOT_SEAT_IMPOSTER", "family": "hot_seat_imposter",
     "text": "What's the last thing you stress-ate at 2am this week?", "spice": 3, "locality": 1, "quality_score": 9},
    {"id": "hot_seat_new_2", "game": "HOT_SEAT_IMPOSTER", "family": "hot_seat_imposter",
     "text": "What would your browser history say if it could talk at your funeral?", "spice": 4, "locality": 1, "quality_score": 10},
    {"id": "hot_seat_new_3", "game": "HOT_SEAT_IMPOSTER", "family": "hot_seat_imposter",
     "text": "What app have you opened and closed 15 times today without doing anything?", "spice": 2, "locality": 1, "quality_score": 9},
    {"id": "hot_seat_new_4", "game": "HOT_SEAT_IMPOSTER", "family": "hot_seat_imposter",
     "text": "What's the most unhinged thing in your Amazon 'Save for Later' right now?", "spice": 3, "locality": 1, "quality_score": 10},
    {"id": "hot_seat_new_5", "game": "HOT_SEAT_IMPOSTER", "family": "hot_seat_imposter",
     "text": "What's your phone lock screen and what does it say about your current mental state?", "spice": 3, "locality": 1, "quality_score": 9},
    # OBSERVABLE BY FRIENDS
    {"id": "hot_seat_new_6", "game": "HOT_SEAT_IMPOSTER", "family": "hot_seat_imposter",
     "text": "What's the thing you do that everyone finds annoying but you refuse to change?", "spice": 3, "locality": 1, "quality_score": 9},
    {"id": "hot_seat_new_7", "game": "HOT_SEAT_IMPOSTER", "family": "hot_seat_imposter",
     "text": "What's your party move when the aux cord gets passed to you?", "spice": 2, "locality": 1, "quality_score": 8},
    {"id": "hot_seat_new_8", "game": "HOT_SEAT_IMPOSTER", "family": "hot_seat_imposter",
     "text": "What's the most embarrassing thing in your Spotify 'On Repeat' right now?", "spice": 3, "locality": 1, "quality_score": 9},
    {"id": "hot_seat_new_9", "game": "HOT_SEAT_IMPOSTER", "family": "hot_seat_imposter",
     "text": "What's your go-to excuse when you need to leave a social event early?", "spice": 3, "locality": 1, "quality_score": 9},
    {"id": "hot_seat_new_10", "game": "HOT_SEAT_IMPOSTER", "family": "hot_seat_imposter",
     "text": "What's the drama you've been silently monitoring in someone else's life?", "spice": 4, "locality": 1, "quality_score": 9},
    # PERSONAL KNOWLEDGE REQUIRED
    {"id": "hot_seat_new_11", "game": "HOT_SEAT_IMPOSTER", "family": "hot_seat_imposter",
     "text": "What's the weirdest thing currently in your fridge that you're pretending doesn't exist?", "spice": 2, "locality": 1, "quality_score": 9},
    {"id": "hot_seat_new_12", "game": "HOT_SEAT_IMPOSTER", "family": "hot_seat_imposter",
     "text": "What's the last lie you told to get out of plans?", "spice": 3, "locality": 1, "quality_score": 9},
    {"id": "hot_seat_new_13", "game": "HOT_SEAT_IMPOSTER", "family": "hot_seat_imposter",
     "text": "What's the pettiest thing you're currently holding a grudge about?", "spice": 4, "locality": 1, "quality_score": 9},
    {"id": "hot_seat_new_14", "game": "HOT_SEAT_IMPOSTER", "family": "hot_seat_imposter",
     "text": "What's the most chaotic text you've sent in the past 24 hours?", "spice": 4, "locality": 1, "quality_score": 9},
    {"id": "hot_seat_new_15", "game": "HOT_SEAT_IMPOSTER", "family": "hot_seat_imposter",
     "text": "What's the one thing about yourself you're convinced no one else knows?", "spice": 4, "locality": 1, "quality_score": 9},
    # BEHAVIOR-BASED
    {"id": "hot_seat_new_16", "game": "HOT_SEAT_IMPOSTER", "family": "hot_seat_imposter",
     "text": "What's the first thing you do when you wake up that you're slightly ashamed of?", "spice": 3, "locality": 1, "quality_score": 9},
    {"id": "hot_seat_new_17", "game": "HOT_SEAT_IMPOSTER", "family": "hot_seat_imposter",
     "text": "What's your 'I'm having a bad day' comfort routine that no one knows about?", "spice": 2, "locality": 1, "quality_score": 8},
    {"id": "hot_seat_new_18", "game": "HOT_SEAT_IMPOSTER", "family": "hot_seat_imposter",
     "text": "What's the most recent thing you Googled that you'd be embarrassed to explain?", "spice": 4, "locality": 1, "quality_score": 10},
    {"id": "hot_seat_new_19", "game": "HOT_SEAT_IMPOSTER", "family": "hot_seat_imposter",
     "text": "What's the last thing you bought that you immediately regretted?", "spice": 2, "locality": 1, "quality_score": 8},
    {"id": "hot_seat_new_20", "game": "HOT_SEAT_IMPOSTER", "family": "hot_seat_imposter",
     "text": "What's the conversation you've been avoiding having with someone?", "spice": 4, "locality": 1, "quality_score": 9},
    # IMPOSTER TRAPS
    {"id": "hot_seat_new_21", "game": "HOT_SEAT_IMPOSTER", "family": "hot_seat_imposter",
     "text": "What's the thing you always say you're going to do but never actually do?", "spice": 2, "locality": 1, "quality_score": 8},
    {"id": "hot_seat_new_22", "game": "HOT_SEAT_IMPOSTER", "family": "hot_seat_imposter",
     "text": "What's your most irrational fear that you know makes no sense?", "spice": 2, "locality": 1, "quality_score": 8},
    {"id": "hot_seat_new_23", "game": "HOT_SEAT_IMPOSTER", "family": "hot_seat_imposter",
     "text": "What's the thing you do that you think is subtle but everyone definitely notices?", "spice": 3, "locality": 1, "quality_score": 9},
    {"id": "hot_seat_new_24", "game": "HOT_SEAT_IMPOSTER", "family": "hot_seat_imposter",
     "text": "What's the one topic that gets you unreasonably passionate?", "spice": 2, "locality": 1, "quality_score": 8},
    {"id": "hot_seat_new_25", "game": "HOT_SEAT_IMPOSTER", "family": "hot_seat_imposter",
     "text": "What's the opinion you have that you know would start an argument?", "spice": 3, "locality": 1, "quality_score": 9},
    # SITUATIONAL
    {"id": "hot_seat_new_26", "game": "HOT_SEAT_IMPOSTER", "family": "hot_seat_imposter",
     "text": "What's your drunk text signature move?", "spice": 4, "locality": 1, "quality_score": 9},
    {"id": "hot_seat_new_27", "game": "HOT_SEAT_IMPOSTER", "family": "hot_seat_imposter",
     "text": "What's the one thing you do when you're alone that you'd never do in public?", "spice": 4, "locality": 1, "quality_score": 9},
    {"id": "hot_seat_new_28", "game": "HOT_SEAT_IMPOSTER", "family": "hot_seat_imposter",
     "text": "What's the most unhinged thing on your bucket list?", "spice": 3, "locality": 1, "quality_score": 8},
    {"id": "hot_seat_new_29", "game": "HOT_SEAT_IMPOSTER", "family": "hot_seat_imposter",
     "text": "What's the thing you're most likely to be doing at 3am on a weeknight?", "spice": 3, "locality": 1, "quality_score": 9},
    {"id": "hot_seat_new_30", "game": "HOT_SEAT_IMPOSTER", "family": "hot_seat_imposter",
     "text": "What's the red flag about yourself that you'd put on a dating app if you were being honest?", "spice": 4, "locality": 1, "quality_score": 10},
    # RELATIONSHIP-FOCUSED
    {"id": "hot_seat_new_31", "game": "HOT_SEAT_IMPOSTER", "family": "hot_seat_imposter",
     "text": "What's the one thing your ex definitely still hates about you?", "spice": 5, "locality": 1, "quality_score": 9},
    {"id": "hot_seat_new_32", "game": "HOT_SEAT_IMPOSTER", "family": "hot_seat_imposter",
     "text": "What's the most chaotic thing you've done for love?", "spice": 4, "locality": 1, "quality_score": 9},
    {"id": "hot_seat_new_33", "game": "HOT_SEAT_IMPOSTER", "family": "hot_seat_imposter",
     "text": "What's the most questionable dating app profile photo you've ever used?", "spice": 4, "locality": 1, "quality_score": 9},
    {"id": "hot_seat_new_34", "game": "HOT_SEAT_IMPOSTER", "family": "hot_seat_imposter",
     "text": "What's your biggest ick that's completely unreasonable?", "spice": 3, "locality": 1, "quality_score": 9},
    {"id": "hot_seat_new_35", "game": "HOT_SEAT_IMPOSTER", "family": "hot_seat_imposter",
     "text": "What's the thing you pretend to like to seem more interesting?", "spice": 3, "locality": 1, "quality_score": 9},
    # LOWER SPICE OPTIONS
    {"id": "hot_seat_new_36", "game": "HOT_SEAT_IMPOSTER", "family": "hot_seat_imposter",
     "text": "What's your go-to comfort movie that you've seen way too many times?", "spice": 1, "locality": 1, "quality_score": 7},
    {"id": "hot_seat_new_37", "game": "HOT_SEAT_IMPOSTER", "family": "hot_seat_imposter",
     "text": "What's the most random thing you've impulse-bought this month?", "spice": 2, "locality": 1, "quality_score": 8},
    {"id": "hot_seat_new_38", "game": "HOT_SEAT_IMPOSTER", "family": "hot_seat_imposter",
     "text": "What's the thing you always order at restaurants even when you say you'll try something new?", "spice": 1, "locality": 1, "quality_score": 8},
    {"id": "hot_seat_new_39", "game": "HOT_SEAT_IMPOSTER", "family": "hot_seat_imposter",
     "text": "What's the rabbit hole you most recently fell into on the internet?", "spice": 2, "locality": 1, "quality_score": 9},
    {"id": "hot_seat_new_40", "game": "HOT_SEAT_IMPOSTER", "family": "hot_seat_imposter",
     "text": "What's the one task on your to-do list that's been there for way too long?", "spice": 1, "locality": 1, "quality_score": 8},
    # MORE QUESTIONS
    {"id": "hot_seat_new_41", "game": "HOT_SEAT_IMPOSTER", "family": "hot_seat_imposter",
     "text": "What's the last song you sang badly in the car?", "spice": 1, "locality": 1, "quality_score": 8},
    {"id": "hot_seat_new_42", "game": "HOT_SEAT_IMPOSTER", "family": "hot_seat_imposter",
     "text": "What's the thing you've been procrastinating on that would take 5 minutes to do?", "spice": 2, "locality": 1, "quality_score": 9},
    {"id": "hot_seat_new_43", "game": "HOT_SEAT_IMPOSTER", "family": "hot_seat_imposter",
     "text": "What's the guilty pleasure you enjoy but tell everyone you hate?", "spice": 2, "locality": 1, "quality_score": 9},
    {"id": "hot_seat_new_44", "game": "HOT_SEAT_IMPOSTER", "family": "hot_seat_imposter",
     "text": "What's the most recent thing you learned that made you feel old?", "spice": 2, "locality": 1, "quality_score": 8},
    {"id": "hot_seat_new_45", "game": "HOT_SEAT_IMPOSTER", "family": "hot_seat_imposter",
     "text": "What's the one thing you'd do differently if you could relive last weekend?", "spice": 3, "locality": 1, "quality_score": 9},
    {"id": "hot_seat_new_46", "game": "HOT_SEAT_IMPOSTER", "family": "hot_seat_imposter",
     "text": "What's the most recent conspiracy theory you considered believing?", "spice": 2, "locality": 1, "quality_score": 8},
    {"id": "hot_seat_new_47", "game": "HOT_SEAT_IMPOSTER", "family": "hot_seat_imposter",
     "text": "What's your most controversial food opinion?", "spice": 2, "locality": 1, "quality_score": 8},
    {"id": "hot_seat_new_48", "game": "HOT_SEAT_IMPOSTER", "family": "hot_seat_imposter",
     "text": "What's the thing you always think you're right about but you're probably wrong?", "spice": 2, "locality": 1, "quality_score": 8},
    {"id": "hot_seat_new_49", "game": "HOT_SEAT_IMPOSTER", "family": "hot_seat_imposter",
     "text": "What's the most unhinged thing in your Notes app right now?", "spice": 3, "locality": 1, "quality_score": 10},
    {"id": "hot_seat_new_50", "game": "HOT_SEAT_IMPOSTER", "family": "hot_seat_imposter",
     "text": "What's the pet peeve that would make you unreasonably angry right now?", "spice": 2, "locality": 1, "quality_score": 8},
]


# ============================================================================
# SCRIPT LOGIC - Merge improvements with existing good cards
# ============================================================================

def main():
    """Main function to create the fixed gold cards JSON."""
    
    # Load existing gold cards
    with open(GOLD_CARDS_PATH) as f:
        existing_cards = json.load(f)
    
    # Define which games need full replacement vs keeping
    GAMES_TO_REPLACE = {
        "REALITY_CHECK",
        "OVER_UNDER", 
        "TEXT_THREAD_TRAP",
        "POISON_PITCH",
        "HOT_SEAT_IMPOSTER",
    }
    
    # Filter out games we're replacing
    cards_to_keep = [c for c in existing_cards if c.get("game") not in GAMES_TO_REPLACE]
    
    # Combine with new cards
    new_cards = (
        REALITY_CHECK_CARDS +
        OVER_UNDER_CARDS +
        TEXT_THREAD_TRAP_CARDS +
        POISON_PITCH_CARDS +
        HOT_SEAT_IMPOSTER_CARDS
    )
    
    all_cards = cards_to_keep + new_cards
    
    # Sort by game name for organization
    all_cards.sort(key=lambda c: (c.get("game", ""), c.get("id", "")))
    
    # Verify counts
    game_counts = {}
    for card in all_cards:
        game = card.get("game", "UNKNOWN")
        game_counts[game] = game_counts.get(game, 0) + 1
    
    print("Gold Cards Distribution:")
    print("-" * 40)
    for game, count in sorted(game_counts.items()):
        status = "✅" if count >= 50 else "⚠️"
        print(f"  {status} {game}: {count} cards")
    print("-" * 40)
    print(f"Total: {len(all_cards)} cards")
    
    # Write output
    output_path = GOLD_CARDS_PATH
    with open(output_path, 'w') as f:
        json.dump(all_cards, f, indent=2)
    
    print(f"\n✅ Fixed gold cards written to: {output_path}")
    
    # Also write a backup
    backup_path = GOLD_CARDS_PATH.with_suffix('.json.backup')
    import shutil
    if not backup_path.exists():
        shutil.copy(GOLD_CARDS_PATH, backup_path)
        print(f"📦 Backup created at: {backup_path}")

if __name__ == "__main__":
    main()
